---
abstract: 'Lazily load packages into your REPL'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
  Test::NoWarnings: 0
  Test::SharedFork: 0
  autodie: 0
  parent: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-REPL-Plugin-LazyLoad
requires:
  Devel::REPL: 0
  perl: v5.8.9
resources:
  bugtracker: https://github.com/hoelzro/devel-repl-plugin-lazyload/issues
  homepage: https://github.com/hoelzro/devel-repl-plugin-lazyload
  repository: https://github.com/hoelzro/devel-repl-plugin-lazyload.git
version: 0.01
